### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties feed.

spring:
  profiles.active: default
---
spring:
  profiles: default   # this is for local development. For QA, Production override these values

spring.jmx:
   enabled: true

server:
  port: 8444
  ssl.key-store: tomcat.keystore
  ssl.key-store-password: lfpa#ad23!@fs
  ssl.keyAlias: tomcat
  ssl.protocol: TLS

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8092
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: black
  version: 0.1
  description: feed upload & download
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

logging.file: /var/log/wizindia/black/backend.log
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR


#jdbc related configs
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/black
  username: black
  password: mypassword

c3p0:
  acquireIncrement: 5
  maxIdleTime: 10800
  initialPoolSize: 10
  minPoolSize: 1
  maxPoolSize: 25
  acquireRetryAttemps: 10
  idleConnectionTestPeriod: 3600
  testConnectionOnCheckin: true

hibernate:
  show_sql: true
  dialect: org.hibernate.dialect.MySQLInnoDBDialect
  format_sql: false
  use_sql_comments: false


